# Generated by Django 2.0.7 on 2022-05-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devusers', '0002_auto_20220508_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
