# Generated by Django 3.2.13 on 2022-05-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devusers', '0003_auto_20220508_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
