# Generated by Django 2.0.7 on 2022-05-09 12:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('devbase', '0002_question_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='date_create',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
